#!/bin/bash

# This script needs bridge-util debian package or similar
# for other distros.

# Run using "source setup-tapif" to get exported PRECONFIGURED_TAPIF variable
# Alternatively, add "export PRECONFIGURED_TAPIF=tap0" to ~/.bashrc

# http://backreference.org/2010/03/26/tuntap-interface-tutorial/

# After executing this script, start example_app.
# Enter 192.168.1.200 or "http://lwip.local/" (Zeroconf)
# in your webbrowser to see example_app webpage.

sudo ip tuntap add dev tap0 mode tap user `whoami`
sudo ip link set tap0 up

sudo ip tuntap add dev tap1 mode tap user `whoami`
sudo ip link set tap1 up

sudo brctl addbr lwipbridge
sudo brctl addif lwipbridge tap0
sudo brctl addif lwipbridge tap1

sudo ip addr add 192.168.1.1/24 dev lwipbridge

sudo ip link set dev lwipbridge up

sudo iptables -A FORWARD -p all -i lwipbridge -j ACCEPT # else L3 won't let the taps communicate with each other
